### ISSUE TITLE
Add instructions on how to update the scripts

### ISSUE THREAD

**Issue by kevmoo** [jodinathan/js_bindings#5]
Put a `readme.md` in the `tool` directory would be a great start.

**Comment by jodinathan** [comment]
I've uploaded an initial `README.md` in the `tool` directory.  

For the moment I am working on the `WebComponents` example and then I will document the dart code and builders.

**Comment by jodinathan** [comment]
Today I use `Map` and `dynamic` calls in the builders because of the JSON stuff from the IDL files.  

Before documenting it full I would like to change the builders to use classes instead, however, for that to happen there is a need for w3c to fix [this issue](https://github.com/w3c/webref/issues/277), so the structure of the JSON will be official.  

Would be nice if anyone seeing this thread to thumbs up that issue please.

**Comment by jodinathan** [comment]
The `readme.md` in the `tool` directory seem fine to understand the scripts.  
I will close this and if you guys have more ideas please open a new issue
